INSERT INTO burgers (id, diets, price, name, description, photo, day)
VALUES
  (1, 'G,L', '14.50', 'Royal Smash', '{"fi": "Smash-tyylinen hampurilainen rapeilla reunoilla, kaksoispihvit, sulatettu cheddar ja kotitekoinen kirpeä kastike.", "en": "Smash-style burger with crispy edges, double beef patties, melted cheddar, and house-made tangy sauce."}', 'royalSmash.jpeg', 'Everyday'),
  (2, 'G', '13.90', 'Bacon BBQ Delight', '{"fi": "Mehevä naudanlihapihvi, savustettu BBQ-kastike, rapea pekoni ja rouskuvat sipulirenkaat.", "en": "Juicy beef patty, smoky BBQ sauce, crispy bacon, and crunchy onion rings."}', 'BBQ.jpeg', 'Everyday'),
  (3, 'L', '12.90', 'Crispy Chicken Classic', '{"fi": "Rapea kanafilee, salaatti, tomaatti ja kermaista valkosipulimajoneesia.", "en": "Crispy chicken fillet, lettuce, tomato, and a creamy garlic mayo."}', 'crispyChicken.jpeg', 'Everyday'),
  (4, 'G', '14.90', 'Blue BBQ Chicken', '{"fi": "Grillattu kanafilee, joka on päällystetty vahvalla sinihomejuustolla, BBQ-kastikkeella ja tuoreella rucolalla.", "en": "Grilled chicken fillet topped with tangy blue cheese, BBQ sauce, and fresh arugula."}', 'blueCheese.jpeg', 'Everyday'),
  (5, 'V', '12.50', 'Veggie Garden Delight', '{"fi": "Mehevä kasvisburgeri grillatulla kasvispihvillä, tuoreilla vihanneksilla ja basilika-aiolilla.", "en": "A hearty vegetarian burger with a grilled veggie patty, fresh greens, and basil aioli."}', 'vege.jpeg', 'Everyday'),
  (6, 'V,G', '13.90', 'Grilled Halloumi Burger', '{"fi": "Grillattua halloumi-juustoa, aurinkokuivattuja tomaatteja, avokadoa ja balsamico-glaseerausta.", "en": "Grilled halloumi cheese, sun-dried tomatoes, avocado, and a balsamic glaze."}', 'halloumi.jpeg', 'Everyday'),
  (7, 'G,L', '13.50', 'Rustic Rye Burger', '{"fi": "Mehevä ruisburgeri naudanlihapihvillä, karamellisoiduilla sipuleilla, säilötyllä kurkulla ja sinappimajoneesilla.", "en": "A hearty rye burger with a beef patty, caramelized onions, pickled cucumber, and mustard mayo."}', '', 'Monday'),
  (8, 'G,L', '14.90', 'Crispy Fish Delight', '{"fi": "Kultaisella paneroinnilla paistettua kalafileetä, salaattia, tartaarkastiketta ja tuoretta tilliä briossileivällä.", "en": "Golden-battered fish fillet with lettuce, tartar sauce, and fresh dill on a brioche bun."}', '', 'Tuesday'),
  (9, 'G,L', '15.90', 'Double Bacon Smash', '{"fi": "Kaksi rapeapintaista smash-pihviä, tupla cheddar-juustoa, rapeaa pekonia ja savustettua BBQ-majoneesia.", "en": "Two crispy-edged smash patties, double cheddar, crispy bacon, and smoky BBQ mayo."}', '', 'Wednesday'),
  (10, 'G,L', '13.90', 'Chicken Avocado Bliss', '{"fi": "Grillattu kanafilee, kermaista avokadoa, salaattia, tomaattia ja valkosipulimajoneesia.", "en": "Grilled chicken breast, creamy avocado slices, lettuce, tomato, and garlic aioli."}', '', 'Thursday'),
  (11, 'L', '14.50', 'Japanese Panko Chicken', '{"fi": "Rapea panko-muroilla kuorrutettu kana, kiinalaista kaalia, makeaa chili-kastiketta ja seesamimajoneesia.", "en": "Crispy panko-breaded chicken, Chinese cabbage, sweet chili sauce, and sesame mayo."}', '', 'Friday'),
  (12, 'G', '14.90', 'Smokey BBQ Burger', '{"fi": "Naudanlihapihvi, marinoitu punasipuli, savustettu BBQ-kastike ja sulatettua gouda-juustoa.", "en": "Beef patty with marinated red onions, smoky BBQ sauce, and melted gouda cheese."}', '', 'Saturday'),
  (13, 'G,L', '13.90', 'Sunday Roast Burger', '{"fi": "Hitaasti paistettua naudanrintaa, piparjuurimajoneesia, karamellisoituja sipuleita ja rucolaa paahdetulla briossileivällä.", "en": "Slow-roasted beef brisket, horseradish mayo, caramelized onions, and arugula on a toasted brioche bun."}', '', 'Sunday');
